---
title: "MB5370 Module 04. Assignment 1 - Plot deconstruction"
output: html_document
date: "2024-05-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
NEM_Data <- read_csv("data/NEM_Data.csv")
View(NEM_Data)
```
```{r}
 New_NEM_Data <- NEM_Data %>%
 mutate(GridScale_PV = Grid_Scale_PV - Wind) %>%
 mutate(DistributedPV = Distributed_PV - Grid_Scale_PV) %>%
 mutate(Hydro_New = Hydro - Distributed_PV) %>%
 mutate(Total = Wind + GridScale_PV + DistributedPV + Hydro_New) %>% 
  select(Year, Wind, GridScale_PV, DistributedPV, Hydro_New, Total)
```

```{r}
New_NEM_Data %>% 
  rename(Grid_Scale_PV = GridScale_PV) %>%
  rename(Distributed_PV = DistributedPV) %>%
  rename(Hydro = Hydro_New)
```

```{r}
New_NEM_Data |>
  pivot_longer(
    cols = Wind:Total,
    names_to = "energy",
    values_to = "values") %>%
ggplot(aes(x = Year, y = values, fill = energy)) +
geom_bar(position = "dodge", stat = "identity") + 
theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}

```

